[package]
name = "rust_music"
version = "0.1.0"
authors = ["James <james@evascend.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
musiclib = {path = "./musiclib"}
periodicsynth = "0.1.6"
cpal = "0.14.2"
